In [311]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from math import sqrt

def t_test(mean_1, std_1, size_1, mean_2, std_2, size_2):
    return abs((mean_1 - mean_2) / sqrt((std_1**2/size_1) + (std_2**2/size_2)))

wo_correction = pd.read_csv("no_correction_err_3_bp_5_2D.csv")
w_correction_5 = pd.read_csv("swap_correction_err_3_bp_5_2D.csv")
# w_correction_4 = pd.read_csv("with_correction_beta_4_err_3.csv")
# w_correction_6 = pd.read_csv("with_correction_beta_6_err_3.csv")
# w_correction_8 = pd.read_csv("with_correction_beta_8_err_3.csv")
wo_correction = wo_correction[pd.notnull(wo_correction['ts_95'])]
w_correction_5 = w_correction_5[pd.notnull(w_correction_5['ts_95'])]
# w_correction_8 = w_correction_8[pd.notnull(w_correction_8['ts_95'])]
colors = ['b', 'c', 'y', 'm', 'r']
#w2=plt.scatter(w_correction_2['er_95'],w_correction_2['ts_95'],color=colors[1], marker='v')
#w4=plt.scatter(w_correction_4['er_95'],w_correction_4['ts_95'],color=colors[3], marker='v')
#w6=plt.scatter(w_correction_6['er_95'],w_correction_6['ts_95'],color=colors[2], marker='v')
#w8=plt.scatter(w_correction_8['er_95'],w_correction_8['ts_95'],color=colors[4], marker='v')
#wo=plt.scatter(wo_correction['er_95'],wo_correction['ts_95'],color=colors[0], marker='o', alpha=.3)

x = w_correction_5['er_95']
y = w_correction_5['ts_95']

z = np.polyfit(x, y, 2)
f = np.poly1d(z)

# calculate new x's and y's
x_new = np.linspace(min(x.values), max(x.values), 50)
y_new = f(x_new)

#t, m, b = np.polyfit(x, y,2)
w5=plt.scatter(w_correction_5['er_95'],w_correction_5['ts_95'],color=colors[0], marker='v')
plt.plot(x_new, y_new, '-',color=colors[0])

# x = w_correction_4['er_95']
# y = w_correction_4['ts_95']
# m, b = np.polyfit(x, y, 1)
# w4=plt.scatter(w_correction_4['er_95'],w_correction_4['ts_95'],color=colors[1], marker='v')
# plt.plot(x, m*x + b, '-',color=colors[1])

# x = w_correction_6['er_95']
# y = w_correction_6['ts_95']
# m, b = np.polyfit(x, y, 1)
# w6=plt.scatter(w_correction_6['er_95'],w_correction_6['ts_95'],color=colors[2], marker='v')
# plt.plot(x, m*x + b, '-',color=colors[2])

# x = w_correction_8['er_95']
# y = w_correction_8['ts_95']
# m, b = np.polyfit(x, y, 1)
# w8=plt.scatter(w_correction_8['er_95'],w_correction_8['ts_95'],color=colors[3], marker='v')
# plt.plot(x, m*x + b, '-',color=colors[3])

x = wo_correction['er_95']
y = wo_correction['ts_95']
#m, b = np.polyfit(x, y, 1)

z = np.polyfit(x, y, 2)
f = np.poly1d(z)

# calculate new x's and y's
x_new = np.linspace(min(x.values), max(x.values), 50)
y_new = f(x_new)

wo=plt.scatter(wo_correction['er_95'],wo_correction['ts_95'],color=colors[4], marker='v')
plt.plot(x_new, y_new, '-',color=colors[4])

plt.legend((w5,wo),
           ('beta = .5','No correction'),
           scatterpoints=1,
           loc='top right',
           ncol=3,
           fontsize=12)
plt.ylabel('Number of steps')
plt.xlabel('Error rate (%)')
plt.show()

In [296]:
df = pd.DataFrame()
df['with beta .5'] = df['ts_95']
# df['with beta .6'] = w_correction_6['ts_95']
# df['with beta .4'] = w_correction_4['ts_95']
# df['with beta .2'] = w_correction_2['ts_95']
df['without'] = wo_correction['ts_95']
print df.describe()
df.hist()
plt.show()
print 'T value for beta .5 = ', t_test(df['with beta .5'].mean(), df['with beta .5'].std(), df['with beta .5'].size, df['without'].mean(), df['without'].std(), df['without'].size)
# print 'T value for beta .4 = ', t_test(df['with beta .4'].mean(), df['with beta .4'].std(), 1000, df['without'].mean(), df['without'].std(), 1000)
# print 'T value for beta .6 = ', t_test(df['with beta .6'].mean(), df['with beta .6'].std(), 1000, df['without'].mean(), df['without'].std(), 1000)
# print 'T value for beta .8 = ', t_test(df['with beta .8'].mean(), df['with beta .8'].std(), 1000, df['without'].mean(), df['without'].std(), 1000)

       with beta .5     without
count    291.000000  291.000000
mean      86.116838  111.982818
std       40.585373   52.087622
min       34.000000   37.000000
25%       56.500000   74.500000
50%       77.000000  100.000000
75%       99.500000  139.500000
max      302.000000  367.000000
T value for beta .5 =  6.68217106668

In [198]:
wo_correction = pd.read_csv("with_correction_30_beta_8_err_3.csv")
wo_correction.describe()

,Unnamed: 0,er,er_80,er_90,er_95,ts_80,ts_90,ts_95
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,499.500000,0.284957,0.283247,0.283853,0.284957,58.126000,61.067000,63.50000
std,288.819436,0.060932,0.065241,0.063116,0.060932,37.915059,37.570761,37.64685
min,0.000000,0.000000,0.000000,0.000000,0.000000,17.000000,19.000000,21.00000
25%,249.750000,0.250000,0.244309,0.243738,0.250000,31.000000,35.000000,37.00000
50%,499.500000,0.294118,0.293725,0.294118,0.294118,45.000000,48.000000,51.00000
75%,749.250000,0.328542,0.329304,0.329624,0.328542,74.250000,76.000000,79.00000
max,999.000000,0.440000,0.458333,0.448980,0.440000,251.000000,258.000000,260.00000

In [199]:
w_correction = pd.read_csv("without_correction_30.csv")
w_correction.describe()

,Unnamed: 0,er,er_80,er_90,er_95,ts_80,ts_90,ts_95
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,499.500000,0.288049,0.287361,0.288078,0.288049,45.722000,51.549000,58.116000
std,288.819436,0.062946,0.069634,0.066568,0.062946,21.756012,22.407269,23.099093
min,0.000000,0.000000,0.000000,0.000000,0.000000,15.000000,19.000000,21.000000
25%,249.750000,0.250000,0.250000,0.250000,0.250000,29.750000,35.000000,40.000000
50%,499.500000,0.293103,0.297297,0.295455,0.293103,40.500000,47.000000,54.000000
75%,749.250000,0.333333,0.340000,0.338028,0.333333,54.250000,62.000000,69.000000
max,999.000000,0.422222,0.431373,0.431818,0.422222,149.000000,151.000000,154.000000

In [306]:
x.values[-1]

0.31428572535499999

In [160]:
colors = ['b', 'c', 'y', 'm', 'r']
#w2=plt.scatter(w_correction_2['er_95'],w_correction_2['ts_95'],color=colors[4], marker='v')
#w4=plt.scatter(w_correction_4['er_95'],w_correction_4['ts_95'],color=colors[3], marker='v')
#w5=plt.scatter(w_correction_5['er_95'],w_correction_5['ts_95'],color=colors[2], marker='v')
#w6=plt.scatter(w_correction_6['er_95'],w_correction_6['ts_95'],color=colors[1], marker='v')
w8=plt.scatter(w_correction_8['er_95'],w_correction_8['ts_95'],color=colors[4], marker='v')
wo=plt.scatter(wo_correction['er_95'],wo_correction['ts_95'],color=colors[0], marker='^', alpha=.5)
plt.legend((w8, wo),
           ('w8', 'wo'),
           scatterpoints=1,
           loc='top right',
           ncol=3,
           fontsize=12)

plt.show()

In [266]:
import numpy as np
import matplotlib.pyplot as plt

# sample data
x = np.arange(10)
y = 5*x + 10 

# fit with np.polyfit

In [267]:
plt.show()

In [314]:
frame

,Unnamed: 0,er,er_80,er_80c,er_90,er_90c,er_95,er_95c,ts_80,ts_80c,ts_90,ts_90c,ts_95,ts_95c
0,0,0.222222,0.238095,0.238095,0.217391,0.217391,0.222222,0.240000,21.0,21.0,23.0,23.0,27.0,25.0
1,1,0.280000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.760000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0.166667,0.117647,0.142857,0.105263,0.125000,0.166667,0.111111,17.0,14.0,19.0,16.0,24.0,18.0
0,0,0.173913,0.176471,0.187500,0.190476,0.200000,0.173913,0.190476,17.0,16.0,21.0,20.0,23.0,21.0
1,1,0.307692,0.315789,0.333333,0.333333,0.350000,0.307692,0.333333,19.0,18.0,24.0,20.0,26.0,24.0
2,2,0.820000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0.420000,0.390244,0.363636,0.377778,0.370370,NaN,0.395349,41.0,22.0,45.0,27.0,NaN,43.0
1,1,0.380000,0.333333,0.342857,0.355556,0.324324,NaN,NaN,36.0,35.0,45.0,37.0,NaN,NaN
2,2,0.540000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0.200000,0.125000,0.142857,0.217391,0.125000,0.200000,0.157895,16.0,14.0,23.0,16.0,25.0,19.0
1,1,0.233333,0.269231,0.280000,0.250000,0.259259,0.233333,0.241379,26.0,25.0,28.0,27.0,30.0,29.0
0,0,0.358974,0.388889,0.400000,0.368421,0.378378,0.358974,0.358974,36.0,35.0,38.0,37.0,39.0,39.0
1,1,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.420000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0.540000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0.440000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0.409091,0.432432,0.423077,0.418605,0.444444,0.409091,0.421053,37.0,26.0,43.0,36.0,44.0,38.0
1,1,0.440000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.660000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0.540000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0.580000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0.333333,0.371429,0.371429,0.351351,0.351351,0.333333,0.333333,35.0,35.0,37.0,37.0,39.0,39.0
1,1,0.518519,0.523810,0.470588,0.478261,0.473684,0.518519,0.458333,21.0,17.0,23.0,19.0,27.0,24.0
2,2,0.820000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0.960000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0.820000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0.413043,0.461538,0.441860,0.441860,0.431818,0.422222,0.413043,39.0,43.0,43.0,44.0,45.0,46.0
1,1,0.260000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0.312500,0.320000,0.320000,0.296296,0.296296,0.312500,0.312500,25.0,25.0,27.0,27.0,32.0,32.0
1,1,0.370370,0.250000,0.250000,0.304348,0.333333,0.370370,0.384615,16.0,16.0,23.0,24.0,27.0,26.0
2,2,0.740000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0.480000,0.500000,0.375000,0.480000,0.511628,NaN,0.511111,48.0,24.0,50.0,43.0,NaN,45.0
1,1,0.275862,0.320000,0.315789,0.296296,0.296296,0.275862,0.275862,25.0,19.0,27.0,27.0,29.0,29.0
0,0,0.192308,0.200000,0.210526,0.208333,0.190476,0.192308,0.208333,20.0,19.0,24.0,21.0,26.0,24.0
1,1,0.238095,0.294118,0.294118,0.263158,0.263158,0.238095,0.238095,17.0,17.0,19.0,19.0,21.0,21.0
0,0,0.130435,0.157895,0.142857,0.142857,0.125000,0.130435,0.157895,19.0,14.0,21.0,16.0,23.0,19.0
1,1,0.346154,0.409091,0.421053,0.375000,0.428571,0.346154,0.391304,22.0,19.0,24.0,21.0,26.0,23.0
2,2,0.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [508]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from math import sqrt
import glob
import math

def t_test(mean_1, std_1, size_1, mean_2, std_2, size_2):
    return abs((mean_1 - mean_2) / sqrt((std_1**2/size_1) + (std_2**2/size_2)))

# print "orignal order of swap:"

# path =r'/home/sahabi/hasan/denoise/data' # use your path
# allFiles = glob.glob(path + "/testing.csv")
# frame = pd.DataFrame()
# list_ = []
# for file_ in allFiles:
#     df = pd.read_csv(file_,index_col=None, header=0)
#     list_.append(df)
# frame = pd.concat(list_)

# frame = frame.dropna()
# colors = ['b', 'c', 'y', 'm', 'r']
# perc = 95
# x = frame['er_{}c'.format(perc)].dropna()
# y = frame['ts_{}c'.format(perc)].dropna() 

# z = np.polyfit(x, y, 2)
# f = np.poly1d(z)

# x_new = np.linspace(min(x.values), max(x.values), 50)
# y_new = f(x_new)

# w5=plt.scatter(x,y,color=colors[0], marker='v')
# plt.plot(x_new, y_new, '-',color=colors[0])


# x = frame['er_{}'.format(perc)].dropna()
# y = frame['ts_{}'.format(perc)].dropna()

# z = np.polyfit(x, y, 2)
# f = np.poly1d(z)

# x_new = np.linspace(min(x.values), max(x.values), 50)
# y_new = f(x_new)

# wo=plt.scatter(frame['er_{}'.format(perc)],frame['ts_{}'.format(perc)],color=colors[4], marker='v')
# plt.plot(x_new, y_new, '-',color=colors[4])

# plt.legend((w5,wo),
#            ('beta = .5','No correction'),
#            scatterpoints=1,
#            loc='top right',
#            ncol=3,
#            fontsize=12)
# plt.ylabel('Number of steps')
# plt.xlabel('Error rate (%)')
# plt.title('Convergence to {}%'.format(perc))
# #plt.show()

# perc = 95
# diff = frame['ts_{}c'.format(perc)].dropna() - frame['ts_{}'.format(perc)].dropna()
# print 't for {}%:'.format(perc),diff.mean()/(diff.std()/sqrt(frame.shape[0]))
# perc = 90
# diff = frame['ts_{}c'.format(perc)].dropna() - frame['ts_{}'.format(perc)].dropna()
# print 't for {}%:'.format(perc),diff.mean()/(diff.std()/sqrt(frame.shape[0]))
# perc = 80
# diff = frame['ts_{}c'.format(perc)].dropna() - frame['ts_{}'.format(perc)].dropna()
# print 't for {}%:'.format(perc),diff.mean()/(diff.std()/sqrt(frame.shape[0]))
path =r'/home/sahabi/hasan/denoise/data'
print "====================================="
print "new order of swap"


allFiles = glob.glob(path + "/data_change_beta_1_real_68.csv")
frame = pd.DataFrame()
list_ = []
for file_ in allFiles:
    df = pd.read_csv(file_,index_col=None, header=0)
    list_.append(df)
frame = pd.concat(list_)

#frame = frame.dropna()
colors = ['b', 'c', 'y', 'm', 'r']
perc = 95
x = frame['er_{}c'.format(perc)].dropna()
y = frame['ts_{}c'.format(perc)].dropna() 

z = np.polyfit(x, y, 2)
f = np.poly1d(z)

x_new = np.linspace(min(x.values), max(x.values), 50)
y_new = f(x_new)

w5l=plt.scatter(x,y,color=colors[0], marker='v')
plt.plot(x_new, y_new, '-',color=colors[0])


x = frame['er_{}'.format(perc)].dropna()
y = frame['ts_{}'.format(perc)].dropna()

z = np.polyfit(x, y, 2)
f = np.poly1d(z)

x_new = np.linspace(min(x.values), max(x.values), 50)
y_new = f(x_new)

wo=plt.scatter(frame['er_{}'.format(perc)],frame['ts_{}'.format(perc)],color=colors[4], marker='x')
plt.plot(x_new, y_new, '-',color=colors[4])

plt.legend((w5,wo),
           ('swap/beta = 1','No correction'),
           scatterpoints=1,
           loc='top right',
           ncol=3,
           fontsize=12)
plt.ylabel('Number of steps')
plt.xlabel('Error rate (%)')
plt.title('Convergence to {}% Labels'.format(perc))
plt.show()

perc = 80
diff = frame['ts_{}c'.format(perc)].dropna() - frame['ts_{}'.format(perc)].dropna()
print 't for {}%:'.format(perc),diff.mean()/(diff.std()/sqrt(frame.shape[0]))
perc = 90
diff = frame['ts_{}c'.format(perc)].dropna() - frame['ts_{}'.format(perc)].dropna()
print 't for {}%:'.format(perc),diff.mean()/(diff.std()/sqrt(frame.shape[0]))
perc = 80
diff = frame['ts_{}c'.format(perc)].dropna() - frame['ts_{}'.format(perc)].dropna()
print 't for {}%:'.format(perc),diff.mean()/(diff.std()/sqrt(frame.shape[0]))

=====================================
new order of swap
t for 80%: -3.87236528596
t for 90%: -4.21601267886
t for 80%: -3.87236528596

In [368]:
frame.to_csv('swap.csv')

In [454]:
path =r'/home/sahabi/hasan/denoise/data/runs'
allFiles = glob.glob(path + "/*.csv")
frame = pd.DataFrame()
list_ = []
trial = 1
for file_ in allFiles:
    df = pd.read_csv(file_,index_col=None, header=0)
    df['trial'] = trial
    trial += 1
    list_.append(df)
frame = pd.concat(list_)

frame = frame.dropna()

In [461]:
frame = frame.sort(['trial','ts'])
frame.to_csv('real_runs.csv')

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [506]:
frame.dropna().shape

(48, 14)

In [509]:
len(x)

50

In [387]:
[(1, 2),(0, 1), (0, 2)]

In [467]:
frame[frame['trial']==1].shape[0]

39

In [398]:
trial = 1
record = pd.DataFrame()
record = record.from_csv('/home/sahabi/hasan/denoise/data/runs.csv')
record = record[record['trial']==trial].actions.values